const STEPS=["Объявления, б/у техника и вакансии","Лизинг, залоги и цикл замены","Сервисы, гидравлика, запчасти и посредники","Перевозчики и автопарк","Тендеры, закупки и контракты","Грузовладельцы и отраслевые предприятия","Суды и весогабаритный контроль","Выставки, союзы и профессиональные сообщества","Инвестиции, господдержка и расширение","Объединение, дедупликация и финальный XLSX"];
const COLS=["Организация","Управляющая компания","ИНН","Город/район","Техника/сегмент","Основание","Телефон","Следующее действие","Почему им нужно звонить / потенциальный интерес к САТ","Руководитель / ЛПР","Выручка последнего подтвержденного года","Численность"];
const STAT=["Показатель","Значение","Единица измерения","Период / дата актуальности","Методика / примечание"];
const REGIONS=["Республика Адыгея","Республика Алтай","Республика Башкортостан","Республика Бурятия","Республика Дагестан","Республика Ингушетия","Кабардино-Балкарская Республика","Республика Калмыкия","Карачаево-Черкесская Республика","Республика Карелия","Республика Коми","Республика Марий Эл","Республика Мордовия","Республика Саха (Якутия)","Республика Северная Осетия — Алания","Республика Татарстан","Республика Тыва","Удмуртская Республика","Республика Хакасия","Чеченская Республика","Чувашская Республика","Алтайский край","Забайкальский край","Камчатский край","Краснодарский край","Красноярский край","Пермский край","Приморский край","Ставропольский край","Хабаровский край","Амурская область","Архангельская область","Астраханская область","Белгородская область","Брянская область","Владимирская область","Волгоградская область","Вологодская область","Воронежская область","Ивановская область","Иркутская область","Калининградская область","Калужская область","Кемеровская область — Кузбасс","Кировская область","Костромская область","Курганская область","Курская область","Ленинградская область","Липецкая область","Магаданская область","Московская область","Мурманская область","Нижегородская область","Новгородская область","Новосибирская область","Омская область","Оренбургская область","Орловская область","Пензенская область","Псковская область","Ростовская область","Рязанская область","Самарская область","Саратовская область","Сахалинская область","Свердловская область","Смоленская область","Тамбовская область","Тверская область","Томская область","Тульская область","Тюменская область","Ульяновская область","Челябинская область","Ярославская область","Москва","Санкт-Петербург","Еврейская автономная область","Ненецкий автономный округ","Ханты-Мансийский автономный округ — Югра","Чукотский автономный округ","Ямало-Ненецкий автономный округ"];
const e={region:document.querySelector("#region"),key:document.querySelector("#apiKey"),start:document.querySelector("#startBtn"),cancel:document.querySelector("#cancelBtn"),pc:document.querySelector("#progressCard"),st:document.querySelector("#statusTitle"),ss:document.querySelector("#statusText"),pct:document.querySelector("#percent"),bar:document.querySelector("#progressBar"),steps:document.querySelector("#steps"),err:document.querySelector("#errorBox"),rc:document.querySelector("#resultCard"),sum:document.querySelector("#resultSummary"),dl:document.querySelector("#downloadBtn"),regions:document.querySelector("#regions")};
REGIONS.forEach(r=>{const o=document.createElement("option");o.value=r;e.regions.append(o)});
STEPS.forEach((s,i)=>{const li=document.createElement("li");li.dataset.step=i;li.innerHTML='<span class="dot">'+(i+1)+'</span><span>'+s+'</span><span class="state">ожидает</span>';e.steps.append(li)});
let ctl=null,blob=null,name=null;
e.cancel.onclick=()=>ctl?.abort();
e.dl.onclick=()=>{if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name||"result.xlsx";document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)};
function step(i,state,note=""){[...e.steps.children].forEach((li,j)=>{li.classList.toggle("active",j===i&&state==="active");if(j===i&&state==="done")li.classList.add("done");if(j===i)li.querySelector(".state").textContent=note||(state==="done"?"готово":"выполняется")});const d=[...e.steps.children].filter(x=>x.classList.contains("done")).length,p=Math.round(d*10);e.pct.textContent=p+"%";e.bar.style.width=p+"%"}
async function load(n){const [c,r]=await Promise.all([fetch("prompts/common.txt",{cache:"no-store"}),fetch("prompts/"+String(n).padStart(2,"0")+".txt",{cache:"no-store"})]);if(!c.ok||!r.ok)throw new Error("Не удалось загрузить инструкцию "+n);return (await r.text())+"\n\n"+(await c.text())}
function contract(final=false){return final?'\n\nТЕХНИЧЕСКИЙ ФОРМАТ: верни ТОЛЬКО валидный JSON без markdown: {"direct_buyers":[],"intermediaries":[],"leasing":[],"statistics":[]}. Коммерческие объекты содержат ровно ключи: '+COLS.map(x=>'"'+x+'"').join(", ")+'. Статистика содержит ровно ключи: '+STAT.map(x=>'"'+x+'"').join(", ")+'. Не добавляй поле "Источник". Если значения нет — пустая строка.':'\n\nТЕХНИЧЕСКИЙ ФОРМАТ: верни ТОЛЬКО валидный JSON без markdown: {"direct_buyers":[],"intermediaries":[],"leasing":[]}. Каждый объект содержит ровно ключи: '+COLS.map(x=>'"'+x+'"').join(", ")+'. Не добавляй поле "Источник". Если значения нет — пустая строка. Не выдумывай данные.'}
function text(d){if(d.output_text)return d.output_text;return(d.output||[]).flatMap(i=>i.type==="message"?(i.content||[]):[]).filter(c=>c.type==="output_text").map(c=>c.text).join("\n")}
function parse(t){t=t.trim().replace(/^\`\`\`(?:json)?\s*/i,"").replace(/\s*\`\`\`$/i,"");try{return JSON.parse(t)}catch{}const a=t.indexOf("{"),b=t.lastIndexOf("}");if(a>=0&&b>a)return JSON.parse(t.slice(a,b+1));throw new Error("Ответ модели не удалось разобрать как JSON")}
async function ask(apiKey,model,input,signal,max=50000){const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+apiKey},body:JSON.stringify({model,tools:[{type:"web_search"}],tool_choice:"required",input,max_output_tokens:max}),signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||("OpenAI API error "+r.status));return parse(text(d))}
function norm(b,stats=false){const o={direct_buyers:Array.isArray(b?.direct_buyers)?b.direct_buyers:[],intermediaries:Array.isArray(b?.intermediaries)?b.intermediaries:[],leasing:Array.isArray(b?.leasing)?b.leasing:[]};if(stats)o.statistics=Array.isArray(b?.statistics)?b.statistics:[];return o}
function sz(b){return(b.direct_buyers?.length||0)+(b.intermediaries?.length||0)+(b.leasing?.length||0)}
function pick(rows,cols){return rows.map(r=>Object.fromEntries(cols.map(c=>[c,r?.[c]??""])))}
function xlsx(b){const wb=XLSX.utils.book_new();[["Прямые покупатели",b.direct_buyers||[],COLS],["Посредники",b.intermediaries||[],COLS],["Лизинг",b.leasing||[],COLS],["Статистика",b.statistics||[],STAT]].forEach(([n,rows,h])=>{const ws=XLSX.utils.json_to_sheet(pick(rows,h),{header:h,skipHeader:false});ws["!cols"]=h.map(x=>({wch:Math.min(48,Math.max(14,x.length+2))}));XLSX.utils.book_append_sheet(wb,ws,n)});return new Blob([XLSX.write(wb,{bookType:"xlsx",type:"array"})],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})}
e.start.onclick=async()=>{const region=e.region.value.trim(),apiKey=e.key.value.trim(),model="gpt-5.6";if(!region)return alert("Выберите или введите регион.");if(!apiKey)return alert("Введите OpenAI API key.");ctl=new AbortController;blob=null;name=null;e.start.disabled=true;e.cancel.disabled=false;e.pc.hidden=false;e.rc.hidden=true;e.err.hidden=true;[...e.steps.children].forEach(li=>{li.className="";li.querySelector(".state").textContent="ожидает"});e.pct.textContent="0%";e.bar.style.width="0%";try{const p=await Promise.all(Array.from({length:10},(_,i)=>load(i+1))),parts=[];for(let i=0;i<9;i++){step(i,"active","исследование");e.st.textContent="Шаг "+(i+1)+" из 10";e.ss.textContent=STEPS[i];const out=norm(await ask(apiKey,model,p[i]+contract(false)+"\n\nРЕГИОН: "+region+"\nВыполни полный поиск именно по этому региону. Web search обязателен.",ctl.signal));parts.push(out);step(i,"done","выполнен · "+sz(out)+" записей")}step(9,"active","финальная дедупликация");e.st.textContent="Шаг 10 из 10";e.ss.textContent=STEPS[9];const fin=norm(await ask(apiKey,model,p[9]+contract(true)+"\n\nРЕГИОН: "+region+"\nНиже единый временный пул результатов шагов 1–9. Считай его эквивалентом входных XLSX. При необходимости используй web_search для точечной перепроверки.\n\nВРЕМЕННЫЙ ПУЛ JSON:\n"+JSON.stringify(parts.map((x,i)=>({step:i+1,name:STEPS[i],data:x}))),ctl.signal,65000),true);blob=xlsx(fin);name="SAT_"+region.replace(/[^a-zа-я0-9_-]+/gi,"_")+".xlsx";step(9,"done","выполнен · "+sz(fin)+" организаций");e.st.textContent="Исследование завершено";e.ss.textContent="Финальный XLSX готов к скачиванию.";e.sum.textContent="Регион: "+region+". Прямые покупатели: "+fin.direct_buyers.length+", посредники: "+fin.intermediaries.length+", лизинг: "+fin.leasing.length+", статистика: "+fin.statistics.length+" строк.";e.rc.hidden=false}catch(err){const a=err?.name==="AbortError";e.err.hidden=false;e.err.textContent=a?"Выполнение остановлено пользователем.":"Ошибка: "+(err?.message||err);e.st.textContent=a?"Остановлено":"Выполнение прервано"}finally{e.start.disabled=false;e.cancel.disabled=true;ctl=null}};
